#!/bin/sh

hypr=$HOME/nixos/modules/home-manager-modules/graphical/hyprland/config
wallpaper_folder=$HOME/Pictures/wallpapers

wallpaper_location="$(ls $wallpaper_folder | wofi --show dmenu)"

$hypr/scripts/variables/set_env background "$wallpaper_folder/$wallpaper_location"

$hypr/scripts/wallpaper/wallpaper

# echo "~/.config/hypr/themes/apatheia/wallpapers$wallpaper"
# swaybg -m fill -i "$HOME/.config/hypr/themes/apatheia/wallpapers/$wallpaper" &
