#!/bin/sh

hypr=$HOME/nixos/modules/home-manager-modules/graphical/hyprland/config
wallpaper_folder=$HOME/Pictures/wallpapers

options=(
    "spirit"
    "lantern"
    # "mushroom"
    # "bunny"
)

selected=${options[ $RANDOM % ${#options[@]} ]}

$hypr/scripts/variables/set_env background "$wallpaper_folder/trees/$selected/optimized.gif"